[package]
name = "envfort"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm-siv = "0.11.1"
argon2 = "0.5.3"
bincode = "3.0.0"
chrono = "0.4.44"
clap = { version = "4.5.60", features = ["derive"] }
getrandom = "0.4.2"
keyring = "3.6.3"
libc = "0.2.182"
rand = "0.10.0"
rpassword = "7.4.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
secrecy = "0.10.3"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
toml = "1.0.3"
uuid = { version = "1.21.0", features = ["v4"] }
zeroize = "1.8.2"
